name: publish_docker

on:
  release:
    types: [created]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}     
      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@master
#      - name: enable experimental mode
#        run: |
#          echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
      # install pipenv
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: pip install docker-squash
        run: |
          pip install docker-squash
      - name: Build, tag, and push image to Dockerhub
        run: |
          docker build -t imranq2/spark_python:${{ steps.previoustag.outputs.tag }} -t imranq2/spark_python:latest .
          docker push imranq2/spark_python:${{ steps.previoustag.outputs.tag }}
          docker push imranq2/spark_python:latest
          docker-squash -t imranq2/spark_python:${{ steps.previoustag.outputs.tag }}-flattened imranq2/spark_python:${{ steps.previoustag.outputs.tag }}
          docker push imranq2/spark_python:${{ steps.previoustag.outputs.tag }}-flattened
